name: Update EVM Addresses

on:
  schedule:
    - cron: '* 20 * * *'  # Run daily at 8pm UTC (3pm EST)
  workflow_dispatch:      # Allow manual triggers

jobs:
  update-evm-addresses:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache jq
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/jq
          key: jq-installation

      - name: Install jq if not cached
        run: |
          if [ ! -f /usr/local/bin/jq ]; then
            sudo apt-get update
            sudo apt-get install -y jq
          fi

      - name: Generate and compare tables
        run: |
          # Create temporary directory for working files
          mkdir -p temp
          
          # Generate new EVM table
          curl -s "https://rest.dev.jp.stork-oracle.network/v1/deployments/evm" | jq -r '
            .data |= map({
              name: (.network | split(" ")[0]),
              subname: (if .network | split(" ")[1:] | length > 0 
                      then .network | split(" ")[1:] | join(" ")
                      else "Mainnet" 
                      end),
              proxy_address: .proxy_address
            }) |
            .data | group_by(.name) | sort_by(.[0].name) |
            map(
              "## \(.[0].name)\n\n| Network | Address |\n| -------- | -------- |\n" + 
              (. | sort_by(.subname) | map("| \(.subname) | `\(.proxy_address)` |") | join("\n")) +
              "\n\n"
            ) | join("")' > temp/new_evm_table.md
          
          # Normalize table formatting for comparison
          if [ -f resources/contract-addresses/evm.md ]; then
            # Extract and normalize existing tables
            sed -n '/^## /,$p' resources/contract-addresses/evm.md | \
              sed 's/|[ ]*\([^|]*\)[ ]*|/|\1|/g' | \
              sed 's/|-*|/-|-/g' | \
              sed 's/| *Network *| *Address *|/|Network|Address|/g' | \
              sed 's/| *- *| *- *|/|-|-|/g' > temp/existing_evm_table_normalized.md
            
            # Normalize new tables
            cat temp/new_evm_table.md | \
              sed 's/|[ ]*\([^|]*\)[ ]*|/|\1|/g' | \
              sed 's/|-*|/-|-/g' | \
              sed 's/| *Network *| *Address *|/|Network|Address|/g' | \
              sed 's/| *- *| *- *|/|-|-|/g' > temp/new_evm_table_normalized.md
            
            # Compare normalized versions
            diff_output=$(diff -w -B temp/new_evm_table_normalized.md temp/existing_evm_table_normalized.md || true)
          else
            diff_output="Initial creation"
          fi
          
          echo "diff_output<<EOF" >> $GITHUB_ENV
          echo "$diff_output" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update EVM addresses file if different
        if: env.diff_output != ''
        run: |
          # Ensure directory exists
          mkdir -p resources/contract-addresses
          
          # Combine header with new table content
          cat temp/header.md temp/new_evm_table.md > resources/contract-addresses/evm.md
          rm -rf temp

      - name: Create Pull Request
        if: env.diff_output != ''
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update EVM Addresses"
          title: "Update EVM Addresses"
          body: "Automated update of the EVM Addresses"
          branch: update-evm-addresses
          delete-branch: true
          base: main
          draft: false